[package]
name = "HashTest"
version = "1.0.0"

[addresses]

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move-on-aptos.git", subdir = "language/move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }
