[package]
name = "basic"
version = "1.0.0"

[addresses]

[dependencies]
MoveStdlib = { git = "https://github.com/joske/move-on-aptos.git", subdir = "language/move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }
