[package]
name = "void"
version = "1.0.0"

[addresses]
std = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "main", addr_subst = { "std" = "0x1" } }
# storage = { local = "../storage" }
