name: Test Coverage

permissions:
  contents: read

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      cache_version: 1

    defaults:
      run:
        # Set the working directory for all steps (so we only build move-to-polka)
        working-directory: language/polkavm/move-to-polka

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          target
        key: ${{ env.cache_version }}-ubuntu-latest-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ env.cache_version }}-ubuntu-latest-cargo-nightly-

    - name: Install LLVM 19
      run: |
        sudo apt update
        sudo apt-get install -y llvm-19 llvm-19-dev lld-19 llvm-19-tools clang-19 libclang-19-dev libpolly-19-dev
        llvm-config-19 --version
        sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-19 100
        echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH

    - name: Enable unprivileged user namespaces
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: Install Rust nightly
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run coverage
      run: cargo tarpaulin --verbose --timeout 120 --out Xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: tarpaulin-report.xml
