name: Quality Assurance move-to-polka

on: push

jobs:
  build-and-test:
    name: Build and Test move-to-polka
    runs-on: ubuntu-latest

    defaults:
      run:
        # Set the working directory for all steps (so we only build move-to-polka)
        working-directory: language/polkavm/move-to-polka

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install LLVM 19
        run: |
          sudo apt update
          sudo apt-get install -y llvm-19 llvm-19-dev lld-19 llvm-19-tools clang-19 libclang-19-dev libpolly-19-dev
          llvm-config-19 --version

      - name: Make sure to use LLVM 19 for the linker
        run: sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-19 100

      - name: Install Rust
        run: |
          rustup toolchain install 1.84.1
          rustup default 1.84.1
          rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Enable unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run tests
        run: cargo test --verbose
